spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/LAB?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  graphql:
    graphiql:
      enabled: true
      printer:
        enabled: true